# in your terminal, run conda: conda env create -f environment.yml
name: timex
channels:
  - conda-forge
  - cmutel
  - diepers
dependencies:
  - bw_timex
  - brightway25 # for Linux/Windows/macOS(x64)
  - bw_temporalis
  - dynamic_characterization
  - matplotlib
  - seaborn
  # - brightway25_nosolver # for macOS ARM machine
  # - scikit-umfpack # for macOS ARM machine
  # - numpy==1.24 # for macOS ARM machine
  # - matplotlib==3.5.2 # for macOS ARM machine
