on:
  push:
    branches:
      - joss_paper
name: Paper Draft

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: joss_paper
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: 'joss'
          paper-path: 'paper.md'
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper